version: "3.4"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - game

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - game

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - game

networks:
  game: