version: "3.4"
services:
  redis:
    image: redis
    networks:
      - game

  rabbitmq:
    image: rabbitmq:management
    networks:
      - game

  mongodb:
    image: mongo
    networks:
      - game

  game:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: target/app.jar
        UTIL_DIR: src/main/docker/
    ports:
      - "9091:9091"
    depends_on:
      - redis
      - rabbitmq
    deploy:
      replicas: 3
    environment:
      - WAIT_FOR_IT=rabbitmq:5672 redis:6379 mongodb:27017
      - JAVA_OPTS=-Xmx512m -Xms256m -Dspring.profiles.active=docker-compose
    networks:
      - game

networks:
  game: