spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    function:
      definition: playerGpsTrackerSupplier;playerGpsTracker;playerCommunication;playerCommunicationSupplier;eventGenerator;eventNotifier;visitEvent;visitEventSupplier;executeAction;executeActionSupplier
    stream:
      bindings:
        playerGpsTrackerSupplier-out-0:
          destination: player.gps.tracker
          binder: rabbit
        playerGpsTracker-in-0:
          destination: player.gps.tracker
          binder: rabbit
          group: player.gps.tracker.persistent
        eventGenerator-in-0:
          destination: player.gps.tracker
          binder: rabbit
          group: event.generator
        eventGenerator-out-0:
          destination: player.communication
          binder: rabbit
        eventNotifier-in-0:
          destination: player.gps.tracker
          binder: rabbit
          group: event.notifier
        eventNotifier-out-0:
          destination: player.communication
          binder: rabbit
        playerCommunicationSupplier-out-0:
          destination: player.communication
          binder: rabbit
        playerCommunication-in-0:
          destination: player.communication
          binder: rabbit
          group: player.communication
        visitEventSupplier-out-0:
          destination: event.visit
          binder: rabbit
        visitEvent-in-0:
          destination: event.visit
          binder: rabbit
          group: event.visit
        visitEvent-out-0:
          destination: player.communication
          binder: rabbit
        executeActionSupplier-out-0:
          destination: event.action
          binder: rabbit
        executeAction-in-0:
          destination: event.action
          binder: rabbit
          group: event.action
        executeAction-out-0:
          destination: player.communication
          binder: rabbit

      rabbit:
        bindings:
          playerGpsTracker-in-0:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true
          eventGenerator-in-0:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true
          eventNotifier-in-0:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true
          playerCommunication-in-0:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true
          visitEvent-in-0:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true
          executeAction-in-0:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true

      binders:
        rabbit:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
server:
  port: 9091

---
spring:
  profiles: docker-compose
  redis:
    host: redis
    port: 6379
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
