package com.game.dto;

public enum MessageType {

    TRACK_GPS,
    VISIT_EVENT,
    EXECUTE_ACTION_EVENT,

    EVENT_NOT_FOUND,
    ACTION_NOT_FOUND,

    EVENT_NOTIFICATION, NEW_EVENT_NOTIFICATION, START_EVENT, UPDATE_EVENT
}
